Repository CodeTrophs/Frontend, pull requests merged in 2021-04, with the labels that each got.

#313 Modified Top button
  .firebase/hosting.b3V0.cache
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/workflows/labels.yml
  .github/workflows/reviewer_assigner.yml
  README.md
  contributing.md
  package-lock.json
  package.json
  pages/login.jsx
  public/SVG/black-search-icon.svg
  public/SVG/subscribe-top.svg
  public/essential_SVG/footer_codetrophs.svg
  public/icons/al-ml-icon.png
  public/icons/angularjs-icon.png
  public/icons/data-science-icon.png
  public/icons/gitPod-icon.png
  public/icons/github-icon.png
  public/icons/react-icon.png
  public/icons/vuejs-icon.png
  public/icons/web-dev-icon.png
  public/images/about-decor.png
  public/images/about-elipse.png
  public/images/aryasoni.jpg
  public/images/home/about-vertical.svg
  public/images/home/welcome-rectangle.svg
  public/images/privacy-decor-left.png
  public/images/privacy-decor-top.png
  public/images/term-decor-left.png
  public/images/term-decor-right.png
  public/images/term-heading.png
  public/logo/codetrophs.png
  public/logo/logo.png
  src/components/AdComponent.jsx
  src/components/FeedCard.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home/WelcomeComponent.jsx
  src/components/ProtectedRoute.jsx
  src/components/SearchBar.jsx
  src/components/ToTop.jsx
  src/scss/searchBar.module.scss
  src/scss/settings.module.scss
  src/scss/toTop.module.scss
  src/seo.js
  src/services/feed.js
  src/services/user.js
Labels: Level0, easy, gssoc2021

#311 Issue Labelling Bot Activated
  .github/workflows/issue_label.yml
Labels: Level1, gssoc2021

#327 navbar added
  .eslintrc.json
  src/components/Header.jsx
  src/components/Nav/Burger.jsx
  src/components/Nav/Navbar.jsx
  src/components/Nav/RightNavbar.jsx
  src/scss/RightNavbar.module.scss
  src/scss/burger.module.scss
  src/scss/navbar.module.scss
Labels: Level 3, gssoc21

#322 testimonial ui improved
  package-lock.json
  package.json
  src/components/Carousel.jsx
  src/scss/carousel.module.scss
Labels: Level2, gssoc21, medium

#321 aligned carousel buttons
  src/scss/carousel.module.scss
Labels: Level0, easy, gssoc21

#346 Fixed Issue #306
  pages/DonateUs.jsx
  src/components/Home/DonateUs.jsx
  src/components/Home/HelpUs.jsx
  src/scss/donate.module.scss
  src/scss/home.module.scss
Labels: Level2, gssoc21, medium
