Repository CodeTrophs/Frontend, pull requests merged in 2021-05, with the labels that each got.

#347 Made responsive for ipad and ipad pro
  .github/workflows/auto-issue-closer.yml
  .github/workflows/issue-assign.yml
  .github/workflows/issue-watcher.yml
  .github/workflows/stale.yml
  package-lock.json
  package.json
  src/components/Carousel.jsx
  src/components/Footer.jsx
  src/scss/footer.module.scss
  src/scss/home.module.scss
Labels: Level1, easy, gssoc21, ready-to-review, under review

#354 Donate us button center aligned new PR
  src/scss/footer.module.scss
  src/scss/home.module.scss
Labels: Level0, gssoc21

#353 Navbar Updated new PR
  package-lock.json
  package.json
  src/components/Header.jsx
  src/components/Nav/Navbar.jsx
  src/components/Navbar/header.jsx
  src/components/Navbar/rule.jsx
  src/scss/navbarNew.module.scss
Labels: Level2, gssoc21, under review

#363 Contact side bar added
  src/components/Home/AboutUs.jsx
Labels: Level2, feature, gssoc21

#364 Issue#288
  src/components/Settings/AboutYou.jsx
  src/components/Settings/Options.jsx
Labels: Level2, feature, gssoc21
